[general]
live_config_reload = true

[terminal.shell]
program = "/usr/bin/env"
args = [ "nu" ]

[bell]
animation = "EaseOutExpo"
duration = 0

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
bold = { family = "JetBrainsMono NFM", style = "Bold" }
italic = { family = "JetBrainsMono NFM", style = "SemiBold Italic" }
normal = { family = "JetBrainsMono NFM", style = "Regular" }
size = 12

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = -5

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
opacity = 1
decorations = "Full"
dynamic_title = true
option_as_alt = "Both"
startup_mode = "Maximized"

[window.dimensions]
columns = 160
lines = 81

[window.padding]
x = 0
y = 0

[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"

[colors.primary]
foreground = "#a9b1d6"
background = '#000000'
# background = "#1a1b26"

# [colors.normal]
# black = '#000000'
# red = '#f2201f'
# green = '#19cb00'
# yellow = '#fffd00'
# blue = '#1a8fff'
# magenta = '#fd28ff'
# cyan = '#14ffff'
# white = '#ffffff'
